/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
AssetsRes._();
  static const String PLUGIN_NAME = 'bazaar';
  static const String PLUGIN_VERSION = '1.0.1+1';
  static const String CATEGORY = 'assets/icons/category.svg';
  static const String NOTIFICATION_BACKGROUND = 'assets/icons/notification_background.svg';
  static const String PROFILE = 'assets/images/profile.svg';
  static const String SCREENSHOT_20240830_203332 = 'assets/screenshots/Screenshot_20240830_203332.png';
  static const String ALL_CATEGORY_SCREEN_2 = 'assets/screenshots/all_category_screen_2.png';
  static const String AUTHORS_DETAILS_SCREEN = 'assets/screenshots/authors_details_screen.png';
  static const String AUTHORS_SCREEN_1 = 'assets/screenshots/authors_screen_1.png';
  static const String AUTHORS_SCREEN_2 = 'assets/screenshots/authors_screen_2.png';
  static const String BOOK_DETAILS = 'assets/screenshots/book_details.png';
  static const String CART_SCREEN_EMPRY = 'assets/screenshots/cart_screen_empry.png';
  static const String CATEGORY_LOADING_SCREEN_1 = 'assets/screenshots/category_loading_screen_1.png';
  static const String CATEGORY_SCREEN_EMPTY = 'assets/screenshots/category_screen_empty.png';
  static const String FEED_SCREEN_1 = 'assets/screenshots/feed_screen_1.png';
  static const String FEED_SCREEN_2 = 'assets/screenshots/feed_screen_2.png';
  static const String FEED_SCREEN_3 = 'assets/screenshots/feed_screen_3.png';
  static const String HOME_SCREEN_EMPTY = 'assets/screenshots/home_Screen_empty.png';
  static const String LOGIN_SCREEN = 'assets/screenshots/login_screen.png';
  static const String LOVE_CATEGORY_SCREEN_3 = 'assets/screenshots/love_category_screen_3.png';
  static const String ONBOARDING_1 = 'assets/screenshots/onboarding_1.png';
  static const String ONBOARDING_2 = 'assets/screenshots/onboarding_2.png';
  static const String ONBOARDING_3 = 'assets/screenshots/onboarding_3.png';
  static const String PROFILE_SCREEN = 'assets/screenshots/profile_screen.png';
  static const String PROFILE_SCREEN_EMPTY = 'assets/screenshots/profile_screen_empty.png';
  static const String RESET_PASSWORD_SCREEN = 'assets/screenshots/reset_password_screen.png';
  static const String SEARCH_SCREEN_1 = 'assets/screenshots/search_screen_1.png';
  static const String SEARCH_SCREEN_2 = 'assets/screenshots/search_screen_2.png';
  static const String SEARCH_SCREEN_3 = 'assets/screenshots/search_screen_3.png';
  static const String SIGNUP_PHONE_SCREEN = 'assets/screenshots/signup_phone_screen.png';
  static const String SIGNUP_SCREEN_1 = 'assets/screenshots/signup_screen_1.png';
  static const String SIGNUP_SCREEN_2 = 'assets/screenshots/signup_screen_2.png';
  static const String SPALSH_SCREEN = 'assets/screenshots/spalsh_screen.png';
  static const String SUCCESS_VRIFICATION = 'assets/screenshots/success_vrification.png';
  static const String UPDATE_PROFILE_SCREEN = 'assets/screenshots/update_profile_screen.png';
  static const String VERIFICATION_PHONE_SCREEN = 'assets/screenshots/verification_phone_screen.png';
}
